version: 2
jobs:
  build:
    docker:
      - image: 552172703831.dkr.ecr.us-west-2.amazonaws.com/infra-tools:latest
        environment:
          AWS_DEFAULT_OUTPUT: json
          AWS_DEFAULT_REGION: us-west-2
    steps:
      - checkout
      - run:
          name: Terraform Init
          working_directory: ~/project/dev
          command: terraform init
      - run:
          name: Terraform Plan
          working_directory: ~/project/dev
          command: terraform plan




